Fix Rust build by reordering libs
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: x86_64-pc-windows-gnu/release/libddnet_engine_shared.a(std-8984bea53711d8dc.std.822af3e2effa3d17-cgu.0.rcgu.o): in function `std::sys::pal::windows::rand::hashmap_random_keys':
/rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys\pal\windows/rand.rs:8: undefined reference to `BCryptGenRandom'

(cherry picked from commit 8459a9af033d2abd1d91882feca1fff71df15f06)