Fix compilation of sphore.cpp on Linux
/ddnet-source/src/base/sphore.cpp: In function ‘void sphore_wait(SEMAPHORE*)’:
/ddnet-source/src/base/sphore.cpp:79:14: error: ‘errno’ was not declared in this scope
   79 |   dbg_assert(errno == EINTR, "sem_wait failure");
      |              ^~~~~
/ddnet-source/src/base/dbg.h:30:8: note: in definition of macro ‘dbg_assert’
   30 |   if(!(test)) \
      |        ^~~~
/ddnet-source/src/base/sphore.cpp:20:1: note: ‘errno’ is defined in header ‘<cerrno>’; did you forget to ‘#include <cerrno>’?
   19 | #include "str.h"
  +++ |+#include <cerrno>
   20 | #endif
In file included from /ddnet-source/src/base/sphore.cpp:6:
/ddnet-source/src/base/sphore.cpp:79:23: error: ‘EINTR’ was not declared in this scope
   79 |   dbg_assert(errno == EINTR, "sem_wait failure");
      |                       ^~~~~
/ddnet-source/src/base/dbg.h:30:8: note: in definition of macro ‘dbg_assert’
   30 |   if(!(test)) \
      |        ^~~~

(cherry picked from commit f8b534e4e020eb36e116bdbbb0eebb4ed04e5881)