Fix compilation in touch_controls.cpp
src/game/client/components/touch_controls.cpp:2366:18: error: ‘LLONG_MAX’ was not declared in this scope
 2366 |  int64_t Delta = LLONG_MAX;
      |                  ^~~~~~~~~

Follow-up to https://github.com/ddnet/ddnet/pull/12035

(cherry picked from commit 80e07f323fc4c136e5afb1bd764eea2da7488915)